### PR TITLE
issue #103 bumping up launch4j to version 3.14

### PR DESCRIPTION
**Pull request by rspido**
- it needs at least java 1.8
- also bumping up version to 2.4.10

### CODE REVIEW

**Comment by TheBoegl** [comment]
Thanks for the PR, I'll merge this soon and release it together with #93 as version 2.0.

**Comment by rspido** [comment]
Thank you for accepting it.
👍

**Comment by rspido** [comment]
@TheBoegl , do you have an ETA for the next release (3.0)?
Thanks

**Comment by TheBoegl** [comment]
I'll try to release a 2.5 with a few deprecations targeting java 6 within this week.
Afterwards we can remove the deprecations and release 3.0 targeting java 8.

**Comment by rspido** [comment]
Fantastic!
Thanks for the update.
👍

**Comment by TheBoegl** [comment]
Had to target java 8 as you did in this PR to meet all launch4j requirements. I overlooked that yesterday when replying to you.

**Pull request merged**
