### PR TITLE
Make closure support for classpath

### PR DESCRIPTION
**Pull request by obearn**
I needed this for my current project.

Example : 
classpath = {
        ["."].plus(project.getConfigurations().getByName("runtime").collect({ "lib/${it.getName()}" })).plus(project.getTasks().getAt(JavaPlugin.JAR_TASK_NAME).getOutputs().getFiles().collect({ "lib/${it.getName()}" }))
    }

I will try to add tests, but for now I can't run them on my mac (I have a branch using wine but it is not working properly for now).

### CODE REVIEW

**Comment by TheBoegl** [comment]
It seems that I've missed this PR before my vacation.

Shouldn't your example work without the closure support?

**Comment by obearn** [comment]
It did not when i tried. I had class cast exception.

Le mar. 5 sept. 2017 à 19:53, Sebastian Bögl <notifications@github.com> a
écrit :

**Comment by TheBoegl** [comment]
You should try to just use `
    classpath = ["."].plus(project.getConfigurations().getByName("runtime").collect({ "lib/${it.getName()}" })).plus(project.getTasks().getAt(JavaPlugin.JAR_TASK_NAME).getOutputs().getFiles().collect({ "lib/${it.getName()}" }))` which should work for your purpose.

**Comment by TheBoegl** [comment]
I'm closing this PR because @obearn didn't comment though I picked dcdd0ba25d6aa546e55db7d907d782e866871938 in cd25cca42a89f5bd218d73b75d4d4068dd0aab10.

**Comment by obearn** [comment]
Sorry, for the late comment, but in my case using your solution I get a gradle error
> Cannot change dependencies of configuration ':compile' after it has been included in dependency resolution.

**Comment by TheBoegl** [comment]
Please provide a link to your project or provide your Gradle build script so I can examine it.

**Pull request closed without merging**
