### PR TITLE
Allow not copy libs

### PR DESCRIPTION
**Pull request by naftalmm**
Allow user to configure plugin (via `copyConfigurable`) in a way when libraryDir will not be created and no files will be copied into it (useful if jar was created via fatJar/shadowJar plugins)

### CODE REVIEW

**Review by TheBoegl — COMMENTED** [review]
@naftalmm Thank you for this PR.
This could be considered as a fix for #68.

**Comment by TheBoegl** [comment]
@naftalmm you did not branch from the develop branch. Either recreate this PR from develop or let me know if I should simply cherry-pick your commits?

**Comment by naftalmm** [comment]
Yes, cherry-pick it, please! Thanks!

**Comment by TheBoegl** [comment]
I'm closing this as the commits are cherry picked in 4439ef1a and 62ba9e82.

**Pull request closed without merging**
